### ISSUE TITLE
Basic project setup.

### ISSUE THREAD

**Issue by piotrleniec** [piotrleniec/awsemo#1]
The very first thing we need to do is to initialize [scrapy](https://github.com/scrapy/scrapy) project. Generated project and a very simple spider which simply visits a site (https://github.com/sindresorhus/awesome) will be sufficient. To make sure it works we can print all the links that can be found in the readme. Scrapy tutorial can be found [here](https://doc.scrapy.org/en/latest/intro/tutorial.html).

**Comment by bielatm** [comment]
Code is ready for code review: https://github.com/piotrleniec/awsemo/pull/3

**Comment by bielatm** [comment]
Solved https://github.com/piotrleniec/awsemo/pull/3
