### ISSUE TITLE
Flat links extraction.

### ISSUE THREAD

**Issue by piotrleniec** [piotrleniec/awsemo#2]
For further analysis, we need to store the data we scrape. The easiest and the most straightforward way to do it is to extract the data to json. Each "object" we scrape will be extracted to a json object which will be aggregated and saved to a file by scrapy. Guidelines how to implement the functionality can be found [here](https://doc.scrapy.org/en/latest/intro/tutorial.html#extracting-data). For now, we will store links in a flat structure (a single array).

**Comment by piotrleniec** [comment]
Blocked by https://github.com/piotrleniec/awsemo/issues/1.

**Comment by piotrleniec** [comment]
No longer blocked by https://github.com/piotrleniec/awsemo/issues/1.

**Comment by bielatm** [comment]
PR https://github.com/piotrleniec/awsemo/pull/8
