### ISSUE TITLE
Frozen dependencies in requirements.txt.

### ISSUE THREAD

**Issue by piotrleniec** [piotrleniec/awsemo#6]
`requirements.txt` file contains a list of all python libraries which are used inside a project. It's a must-have if we want to have repeatable builds. The documentation can be found [here](https://pip.pypa.io/en/stable/user_guide/).

**Comment by bielatm** [comment]
The link to the documentation is incorrect.

**Comment by piotrleniec** [comment]
Sorry for that! I've fixed the link.

**Comment by bielatm** [comment]
PR https://github.com/piotrleniec/awsemo/pull/9
